### ISSUE TITLE
netstandard2.x plz

### ISSUE THREAD

**Issue by sekkit** [cloudtoid/interprocess#10]
Wanna use it inside Unity. Plz support netstandard compilation.

**Comment by pedramrezaei** [comment]
That seems like a fun project. Any takers from the community?

The current implementation relies on named semaphores. Need to make sure it is available in netstandard.

**Comment by sekkit** [comment]
netfx 4.x also meet that needs.

**Comment by prezaei** [comment]
Reading [this](https://docs.unity3d.com/Manual/overview-of-dot-net-in-unity.html) we would need to remove all async/await uses and ensure all .net APIs are compatible with Unity. This is probably a full rewrite and might not be as fast as the current optimized implementation. Right?

**Comment by sekkit** [comment]
> Reading [this](https://docs.unity3d.com/Manual/overview-of-dot-net-in-unity.html) we would need to remove all async/await uses and ensure all .net APIs are compatible with Unity. This is probably a full rewrite and might not be as fast as the current optimized implementation. Right?

I guess we don't need to use any Unity API and Async/await is working inside Unity.

**Comment by TYoungSL** [comment]
SL's fork (https://github.com/StirlingLabs/interprocess/) does add .NET standard 2.0, 2.1 support.

**Comment by sekkit** [comment]
> SL's fork (https://github.com/StirlingLabs/interprocess/) does add .NET standard 2.0, 2.1 support.

great, thx.
