### ISSUE TITLE
Publisher message length check overflow

### ISSUE THREAD

**Issue by RyanYANG52** [cloudtoid/interprocess#15]
Hi, cloudtoid

in publisher code, message length needs to be small than capacity, if `tailoffset` is great than `long.MaxLength`, it will SafeIncrement to a negative value, so this line here should check if `TailOffset < HeadOffset`

https://github.com/cloudtoid/interprocess/blob/e2768b0be556ae13f0bc1d673f00f7e3f9c2ada5/src/Interprocess/Queue/Publisher.cs#L34

great work by the work

**Comment by RyanYANG52** [comment]
this line here, if a message is split by `long.MaxValue` perfectly, `headerOffset = long.MaxValue - 8`, `bodyOffset` should be 0, but here is `long.MinValue`. 

``` csharp
// this way should be ok
SafeIncrementMessageOffset(messageHeaderOffset, sizeof(MessageHeader));
```

https://github.com/cloudtoid/interprocess/blob/e2768b0be556ae13f0bc1d673f00f7e3f9c2ada5/src/Interprocess/Queue/Queue.cs#L66

**Comment by prezaei** [comment]
Hi @RyanYANG52 , can you provide a quick repro? Thanks

**Comment by RyanYANG52** [comment]
I think this test should pass, right
```csharp
        [Fact]
        public unsafe void OverflowEnqueue()
        {
            using var p = (CreatePublisher(1024) as Publisher)!;

            // simulate write and read empty header until here
            p.Header->HeadOffset = 8 * (long.MaxValue / 8);
            p.Header->TailOffset = 8 * (long.MaxValue / 8);

            var message = new byte[8];

            p.TryEnqueue(message).Should().BeTrue();
            p.TryEnqueue(message).Should().BeTrue();
        }
```

**Comment by prezaei** [comment]
Hey @RyanYANG52 , Is your queue capacity set to `8 * (long.MaxValue / 8)` or something higher than half of that?

**Comment by RyanYANG52** [comment]
```csharp
        protected long SafeIncrementMessageOffset(long offset, long increment)
            => (offset + increment) % Buffer.Capacity;
```
If using `% Capacity` instead of `long.MaxValue`, `messageLength` should be less than `Buffer.Capacity`
```csharp
                if (tailOffset >= headOffset)
                {
                    if (messageLength >= Buffer.Capacity - (tailOffset - headOffset))
                        return false;
                }
                else
                {
                    if (messageLength >= headOffset - tailOffset)
                        return false;
                }
```
for example,  this test should not pass
```csharp
            using var p = CreatePublisher(48);
            // p.Buffer.Capacity == 32; (48 - 16)

            p.TryEnqueue(ByteArray3).Should().BeTrue();
            // HeaderOffset == 0; TailOffset == 16;
            p.TryEnqueue(ByteArray3).Should().BeTrue();
            // HeaderOffset == 16; TailOffset == 0;
            p.TryEnqueue(ByteArray3).Should().BeTrue();
            // HeaderOffset == 0; TailOffset == 16;
```

**Comment by RyanYANG52** [comment]
```csharp
            if (increment > long.MaxValue - offset)
                return -long.MaxValue + offset + increment; // Do NOT change the order of additions here
```

another detail I noticed is in the old approach, why use `-long.MaxValue` instead of `long.MinValue`, 
`8 * (long.MaxValue / 8)` increment 8 would be `1`, not `0`

**Comment by RyanYANG52** [comment]
yeah, it has lots of corner cases, try this test

```csharp
            using (var p = CreatePublisher(48))
            {
                p.TryEnqueue(ByteArray50).Should().BeFalse(); // failed here
            }
```

```csharp
if (tailOffset != headOffset) 
{
...
} 
else
{ 
// check messageLength is less or equal than Capacity
}
```

**Comment by pedramrezaei** [comment]
Nice. @RyanYANG52 ... Try out the latest? Thanks for all the help man.

**Comment by prezaei** [comment]
Nice. @RyanYANG52 ... Try out the latest? Thanks for all the help man.

**Comment by RyanYANG52** [comment]
you are welcome, and all works well
