### ISSUE TITLE
This library don't support multiple subscribers.

### ISSUE THREAD

**Issue by happysammy** [cloudtoid/interprocess#2]
I test the sample publisher and subscriber on windows10 OS,  then find that  it doesn't support multiple subscribers. I start a publisher process and two same subscriber processes (called A and B), but subscriber A  receive different data compared with subscriber B, so maybe this is a bug. Some screenshots are as follows.
![image](https://user-images.githubusercontent.com/6129408/101114432-69fb6780-361c-11eb-9aa6-3cd2d4942177.png)
![image](https://user-images.githubusercontent.com/6129408/101114465-7f709180-361c-11eb-8b3e-00b09d7cc12e.png)
![image](https://user-images.githubusercontent.com/6129408/101114486-8e574400-361c-11eb-99f1-602f2267b6eb.png)

**Comment by pedramrezaei** [comment]
@happysammy, this is a queue and not a broadcast channel. One queue, multiple publishers and multiple subscribers. Once a message is read by one subscriber, it is removed from the queue. HTH

**Comment by happysammy** [comment]
Thanks.
