### ISSUE TITLE
Start Subscriber at Head Instead of Tail

### ISSUE THREAD

**Issue by cocowalla** [cloudtoid/interprocess#4]
Hi, thanks for this nice library! 🙏 

I was playing with the sample, and noticed that when the Subscriber starts, it reads back any existing queued messages first. What I'd like is for the Subscriber to only read new messages from that point onwards. Would that be possible?

**Comment by prezaei** [comment]
Hey, thanks. Have you tried adding a time stamp to your messages ignoring the ones that you are interested in? There is no easy way to do this in the library today.
