### ISSUE TITLE
Add support for setting MMF security [feature request]

### ISSUE THREAD

**Issue by cocowalla** [cloudtoid/interprocess#5]
If the 2 processes are running as the same user, there is no problem with security. But if you want 2 processes with different users to communicate, you will get "access denied".

In .NET Framework this was possible using `MemoryMappedFileSecurity` - but, bizarelly, [Microsoft have chosen not to add support for this](https://github.com/dotnet/runtime/issues/941) in .NET Core/.NET 5/6.

The request here is to add the interop plumbing to allow setting an ACL for MMFs (I did something similar a while back, when Microsoft made the same bizare decision for named pipes; not sure if they ever did implement ACLs there).

**Comment by prezaei** [comment]
Duplicate of #6
